branch-defaults:
  main:
    environment: Djangocicd-env
environment-defaults:
  crm-lsc-group-env:
    branch: null
    repository: null
global:
  application_name: djangocicd
  default_ec2_keyname: my-key-pair
  default_platform: Python 3.11 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
